### ISSUE TITLE
throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by pierrenel** [ewiner/sonoslack#4]
Weird :( 

I'm running node version 0.12.0 - it's seems to be getting the track from Sonos... so not entirely sure why it's unhappy.

```
# pierre at Pierre.local in ~/Code/sonoslack on git:master x [11:41:04]
$ ./index.iced
Late Night Tales - Late Night Tales Cinematic Mix
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect ECONNREFUSED
  at exports._errnoException (util.js:746:11)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```

**Comment by simonbrickle** [comment]
Hi pierre, I have the same issue - did you manage to resolve it?

**Comment by pierrenel** [comment]
@simonbrickle - nope, I ended up using https://github.com/josheverett/slack-sonos-scrobbler instead :(

**Comment by jonadair** [comment]
Same issue here... let me know if anyone works out a fix!

**Comment by dbernazal** [comment]
The album art is breaking this. If you remove https://github.com/ewiner/sonoslack/blob/master/index.iced#L56-L57 and https://github.com/ewiner/sonoslack/blob/master/index.iced#L72 you can get the basic artist/song messaging to work. Haven't been able to fix the album art though.

**Comment by N1ck** [comment]
I've fixed it here: https://github.com/ewiner/sonoslack/pull/5

:+1: :tada:
